INSERT INTO workspace.default.sports_federations_safeguarding_country (
    Federation,
    Sport,
    Country,
    CodeofEthics,
    CodeofConduct,
    SpecialEntityDedicated
)
VALUES
    ('DFB', 'Football', 'Germany', 'Y', 'Y', 'Y'),
    ('DFB', 'Basketball', 'Germany', 'Y', 'Y', 'N'),
    ('DFB', 'Athletics', 'Germany', 'Y', 'N', 'Y'),
    ('DFB', 'Swimming', 'Germany', 'Y', 'Y', 'Y'),
    ('DFB', 'Volleyball', 'Germany', 'N', 'Y', 'N'),
    ('FFF', 'Football', 'France', 'Y', 'Y', 'Y'),
    ('FFF', 'Basketball', 'France', 'Y', 'N', 'N'),
    ('FFF', 'Athletics', 'France', 'Y', 'Y', 'Y'),
    ('FFF', 'Swimming', 'France', 'Y', 'Y', 'N'),
    ('FFF', 'Volleyball', 'France', 'N', 'Y', 'Y'),
    ('RFEF', 'Football', 'Spain', 'Y', 'Y', 'N'),
    ('RFEF', 'Basketball', 'Spain', 'Y', 'Y', 'Y'),
    ('RFEF', 'Athletics', 'Spain', 'N', 'Y', 'N'),
    ('RFEF', 'Swimming', 'Spain', 'Y', 'N', 'Y'),
    ('RFEF', 'Volleyball', 'Spain', 'Y', 'Y', 'Y'),
    ('FIGC', 'Football', 'Italy', 'Y', 'N', 'Y'),
    ('FIGC', 'Basketball', 'Italy', 'Y', 'Y', 'N'),
    ('FIGC', 'Athletics', 'Italy', 'Y', 'Y', 'Y'),
    ('FIGC', 'Swimming', 'Italy', 'N', 'Y', 'N'),
    ('FIGC', 'Volleyball', 'Italy', 'Y', 'Y', 'Y'),
    ('KNVB', 'Football', 'Netherlands', 'Y', 'Y', 'Y'),
    ('KNVB', 'Basketball', 'Netherlands', 'Y', 'Y', 'N'),
    ('KNVB', 'Athletics', 'Netherlands', 'Y', 'N', 'Y'),
    ('KNVB', 'Swimming', 'Netherlands', 'Y', 'Y', 'Y'),
    ('KNVB', 'Volleyball', 'Netherlands', 'N', 'Y', 'N'),
    ('RBFA', 'Football', 'Belgium', 'Y', 'Y', 'N'),
    ('RBFA', 'Basketball', 'Belgium', 'Y', 'N', 'Y'),
    ('RBFA', 'Athletics', 'Belgium', 'Y', 'Y', 'Y'),
    ('RBFA', 'Swimming', 'Belgium', 'N', 'Y', 'N'),
    ('RBFA', 'Volleyball', 'Belgium', 'Y', 'Y', 'Y'),
    ('FPF', 'Football', 'Portugal', 'Y', 'Y', 'Y'),
    ('FPF', 'Basketball', 'Portugal', 'Y', 'Y', 'N'),
    ('FPF', 'Athletics', 'Portugal', 'N', 'Y', 'Y'),
    ('FPF', 'Swimming', 'Portugal', 'Y', 'N', 'N'),
    ('FPF', 'Volleyball', 'Portugal', 'Y', 'Y', 'Y'),
    ('OFB', 'Football', 'Austria', 'Y', 'N', 'Y'),
    ('OFB', 'Basketball', 'Austria', 'Y', 'Y', 'N'),
    ('OFB', 'Athletics', 'Austria', 'Y', 'Y', 'Y'),
    ('OFB', 'Swimming', 'Austria', 'N', 'Y', 'N'),
    ('OFB', 'Volleyball', 'Austria', 'Y', 'Y', 'Y'),
    ('SFV', 'Football', 'Switzerland', 'Y', 'Y', 'N'),
    ('SFV', 'Basketball', 'Switzerland', 'Y', 'Y', 'Y'),
    ('SFV', 'Athletics', 'Switzerland', 'Y', 'N', 'N'),
    ('SFV', 'Swimming', 'Switzerland', 'Y', 'Y', 'Y'),
    ('SFV', 'Volleyball', 'Switzerland', 'N', 'Y', 'N'),
    ('SvFF', 'Football', 'Sweden', 'Y', 'Y', 'Y'),
    ('SvFF', 'Basketball', 'Sweden', 'Y', 'N', 'N'),
    ('SvFF', 'Athletics', 'Sweden', 'Y', 'Y', 'Y'),
    ('SvFF', 'Swimming', 'Sweden', 'N', 'Y', 'Y'),
    ('SvFF', 'Volleyball', 'Sweden', 'Y', 'Y', 'N'),
    ('NFF', 'Football', 'Norway', 'Y', 'Y', 'N'),
    ('NFF', 'Basketball', 'Norway', 'Y', 'Y', 'Y'),
    ('NFF', 'Athletics', 'Norway', 'N', 'Y', 'N'),
    ('NFF', 'Swimming', 'Norway', 'Y', 'N', 'Y'),
    ('NFF', 'Volleyball', 'Norway', 'Y', 'Y', 'Y'),
    ('DBU', 'Football', 'Denmark', 'Y', 'N', 'Y'),
    ('DBU', 'Basketball', 'Denmark', 'Y', 'Y', 'N'),
    ('DBU', 'Athletics', 'Denmark', 'Y', 'Y', 'Y'),
    ('DBU', 'Swimming', 'Denmark', 'N', 'Y', 'N'),
    ('DBU', 'Volleyball', 'Denmark', 'Y', 'Y', 'Y'),
    ('SUL', 'Football', 'Finland', 'Y', 'Y', 'Y'),
    ('SUL', 'Basketball', 'Finland', 'Y', 'Y', 'N'),
    ('SUL', 'Athletics', 'Finland', 'Y', 'N', 'Y'),
    ('SUL', 'Swimming', 'Finland', 'Y', 'Y', 'Y'),
    ('SUL', 'Volleyball', 'Finland', 'N', 'Y', 'N'),
    ('FAI', 'Football', 'Ireland', 'Y', 'Y', 'N'),
    ('FAI', 'Basketball', 'Ireland', 'Y', 'N', 'Y'),
    ('FAI', 'Athletics', 'Ireland', 'Y', 'Y', 'Y'),
    ('FAI', 'Swimming', 'Ireland', 'N', 'Y', 'N'),
    ('FAI', 'Volleyball', 'Ireland', 'Y', 'Y', 'Y'),
    ('PZPN', 'Football', 'Poland', 'Y', 'Y', 'Y'),
    ('PZPN', 'Basketball', 'Poland', 'Y', 'Y', 'N'),
    ('PZPN', 'Athletics', 'Poland', 'N', 'Y', 'Y'),
    ('PZPN', 'Swimming', 'Poland', 'Y', 'N', 'N'),
    ('PZPN', 'Volleyball', 'Poland', 'Y', 'Y', 'Y'),
    ('FACR', 'Football', 'Czech Republic', 'Y', 'N', 'Y'),
    ('FACR', 'Basketball', 'Czech Republic', 'Y', 'Y', 'N'),
    ('FACR', 'Athletics', 'Czech Republic', 'Y', 'Y', 'Y'),
    ('FACR', 'Swimming', 'Czech Republic', 'N', 'Y', 'N'),
    ('FACR', 'Volleyball', 'Czech Republic', 'Y', 'Y', 'Y'),
    ('HFF', 'Football', 'Greece', 'Y', 'Y', 'N'),
    ('HFF', 'Basketball', 'Greece', 'Y', 'Y', 'Y'),
    ('HFF', 'Athletics', 'Greece', 'Y', 'N', 'N'),
    ('HFF', 'Swimming', 'Greece', 'Y', 'Y', 'Y'),
    ('HFF', 'Volleyball', 'Greece', 'N', 'Y', 'N'),
    ('CBF', 'Football', 'Brazil', 'Y', 'Y', 'Y'),
    ('CBF', 'Basketball', 'Brazil', 'Y', 'N', 'N'),
    ('CBF', 'Athletics', 'Brazil', 'Y', 'Y', 'Y'),
    ('CBF', 'Swimming', 'Brazil', 'N', 'Y', 'N'),
    ('CBF', 'Volleyball', 'Brazil', 'Y', 'Y', 'Y'),
    ('Canada Soccer', 'Football', 'Canada', 'Y', 'Y', 'N'),
    ('Canada Soccer', 'Basketball', 'Canada', 'Y', 'Y', 'Y'),
    ('Canada Soccer', 'Athletics', 'Canada', 'N', 'Y', 'N'),
    ('Canada Soccer', 'Swimming', 'Canada', 'Y', 'N', 'Y'),
    ('Canada Soccer', 'Volleyball', 'Canada', 'Y', 'Y', 'Y'),
    ('JFA', 'Football', 'Japan', 'Y', 'N', 'Y'),
    ('JFA', 'Basketball', 'Japan', 'Y', 'Y', 'N'),
    ('JFA', 'Athletics', 'Japan', 'Y', 'Y', 'Y'),
    ('JFA', 'Swimming', 'Japan', 'N', 'Y', 'N'),
    ('JFA', 'Volleyball', 'Japan', 'Y', 'Y', 'Y');
